# Setup LDAP authentication for netboot clients.
#
# Netboot nodes will authenticate via LDAP to the `ldap_server` (typically the
# head node).
---
- hosts: netboot_root
  gather_facts: false
  become: true
  tasks:
    - name: install LDAP client packages
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - libpam-ldap
        - ldap-utils
        - libnss-ldap

    - name: template ldap.conf file to /etc
      template:
        src: 'files/netboot/etc/ldap.conf'
        dest: '/etc/ldap.conf'

    # In the future we may switch to using `pam-auth-update` if things start
    # getting complicated, but this simple approach works for now.
    - name: update nsswitch.conf
      lineinfile:
        path: '/etc/nsswitch.conf'
        line: "{{ '{:<15}'.format(item + ':') }} files ldap"
        regexp: '^{{ item }}'
        state: present
      loop:
        - passwd
        - group
        - shadow
