# Ansible playbook to create the `netboot-persistent.target` file and the
# `multi-user.target.wants/netboot-persistent.target` symlink that points to
# it in the netboot root file system's /etc/systemd/system` directory.
#
# It also installs a config file in the netboot root's `/etc/tmpfiles.d`
# directory.  This config file has two purposes:
#
# 1. To ensure that the `netboot-persistent.target.wants` directory exists in
#    the netboot host's `/persistent/etc/systemd/system` directory at boot
#    time.
# 2. To create a `netboot-persistent.target.wants` symlink in the netboot
#    root's `/etc/systemd/system` directory pointing to 
#    `../../../persistent/etc/systemd/system/netboot-persistent.target.wants`
#
# This config file is executed as part of the playbook so ensure that the
# symlink in `/etc/...` will already exist when the config file is run on the
# netboot hosts at boot time.
#
# The end result is:
#
# $netboot_root/
# |-- etc/
# |   `-- systemd/
# |       `-- system/
# |           |-- multi-user.target.wants/
# |           |   `-- !netboot-persistent.target -> ../netboot-persistent.target
# |           |-- !netboot-persistent.target
# |           `-- !netboot-persistent.target.wants -> ../../../persisient/etc/systemd/system/netboot-persistent.target.wants
# `-- persistent/
#     `-- etc/
#         `-- systemd/
#             `-- system/
#                 `-- *netboot-persistent.target.wants/
#
# On the netboot hosts, the result will be:
#
# /persistent/
# `-- etc/
#     `-- systemd/
#         `-- system/
#             `-- *netboot-persistent.target.wants/
#
# - Items marked by `!` are created by this playbook.
# - Items marked by `*` are created by systemd-tmpfiles
#
# This allows services to be enabled on a per-host basis by creating a symlink
# in the hosts' /persistent/etc/systemd/system/netboot-persistent.target.wants
# directory.
---
- hosts: netboot_root
  gather_facts: false
  become: true
  tasks:
    - name: create netboot-persistent.target
      copy:
        content: |
          [Unit]
          Description=Netboot persistent target

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/netboot-persistent.target
        owner: root
        group: root
        mode: '0644'

    - name: add netboot-persistent.target to multi-user.wants
      file:
        state: link
        path: /etc/systemd/system/multi-user.target.wants/netboot-persistent.target
        src: ../netboot-persistent.target

    - name: install /etc/tmpfiles.d/netboot-systemd.conf
      copy:
        src: files/netboot/etc/tmpfiles.d/netboot-systemd.conf
        dest: /etc/tmpfiles.d
        owner: root
        group: root
        mode: '0644'

    - name: run systemd-tmpfiles
      command: systemd-tmpfiles --create /etc/tmpfiles.d/netboot-systemd.conf
