# Ansible playbook to setup the netplan config files for the network interfaces
# defined in the `net_ifaces` dictionary.
---
- hosts: head_nodes
  gather_facts: false
  become: true
  tasks:
    - name: ensure persistent netplan directories exists
      file:
        state: directory
        path: "{{ persistent_root }}/{{ hostvars[item].canonical_name }}/etc/netplan"
        owner: "root"
        group: "root"
        mode: "0755"
      loop: "{{ groups.netboot_nodes }}"

    - name: create netplan files
      template:
        src: persistent/etc/netplan/interfaces.yaml
        dest: "{{ persistent_root }}/{{ item }}/etc/netplan/interfaces.yaml"
        owner: root
        group: root
        mode: '0644'
      vars:
        net_ifaces: "{{ hostvars[item].net_ifaces }}"
      loop: "{{ groups.netboot_nodes }}"
      loop_control:
        label: "{{ item }}"
