# Setup rsyslog on for netboot cluster.
#
# Netboot nodes to send log messages to the head node via UDP port 514.
# Head node logs netboot messages to `/var/log/<HOSTNAME>` (on head node).
---
- hosts: head_nodes
  gather_facts: false
  become: true
  tasks:
    - name: ensure rsyslog package is installed
      apt:
        name: rsyslog
        state: present
    - name: template conf files to /etc/rsyslog.d
      template:
        src: 'files/headnode/etc/rsyslog.d/{{ item }}'
        dest: '/etc/rsyslog.d/{{ item }}'
      loop:
        - 10-enable-udp.conf
        - 10-file-create-mode-0644.conf
        - 10-netboot-remote.conf
    - name: restart rsyslogd
      systemd:
        name: rsyslog.service
        state: restarted

- hosts: netboot_root
  gather_facts: false
  become: true
  tasks:
    - name: ensure rsyslog package is installed
      apt:
        name: rsyslog
        state: present
    - name: template conf files to /etc/rsyslog.d
      template:
        src: 'files/netboot/etc/rsyslog.d/{{ item }}'
        dest: '/etc/rsyslog.d/{{ item }}'
      loop:
        - 99-send-all-to-head-node.conf
