# Setup time synchronization for netboot cluster.
#
# NTP is used on the head node while systemd-timesyncd is used on the netboot
# nodes.
#
# The head node will only be configured if the `config_headnode` variable is
# explicitly specified as `true` on the `ansible-playbook` command line using
# `-e config_headnode=true`.
---
- hosts: head_nodes
  gather_facts: false
  become: true
  vars:
    # Override on command line with "-e 'config_headnode=true'"
    config_headnode: false
  tasks:
    - name: ensure ntp package is installed
      apt:
        name: ntp
        state: present
      when: config_headnode

    - name: template conf files to /etc/rsyslog.d
      template:
        src: 'files/headnode/etc/ntp.conf'
        dest: '/etc/ntp.conf'
      when: config_headnode

    - name: restart ntp
      systemd:
        name: ntp.service
        state: restarted
      when: config_headnode and "not ansible_check_mode"

- hosts: netboot_root
  gather_facts: false
  become: true
  tasks:
    - name: ensure systemd-timesyncd package is installed
      apt:
        name: systemd-timesyncd
        state: present
